import { create } from 'zustand';

import {
  // Showcase
  monitors,
  flyingBananas,
  roomWithSoftShadows,
  tshirtConfigurator,
  caustics,
  volumetricLightGodray,
  enterPortals,
  passThroughPortals,
  magicBox,
  glassFlower,
  imageGallery,
  horizontalTiles,
  bestServedBoldChristmasBaubles,
  theThreeGraces,
  frostedGlass,
  gltfjsx400kbDrone,
  starWars,
  brunoSimons20kChallenge,
  scrollcontrolsAndLensRefraction,
  buildingDynamicEnvmaps,
  nextjsPrism,
  buildingLiveEnvmaps,
  shoeConfigurator,
  audioAnalyser,
  groundReflectionsAndVideoTextures,
  threejsJourneyLv1,
  threejsJourneyPortal,
  mixingHtmlAndWebglWithOcclusion,
  interactiveSplineSceneLiveHtml,
  diamondRefraction,
  diamondRing,
  envmapGroundProjection,
  splineGlassShapes,
  csgBunnyUsegroups,
  csgHouse,
  gltfAnimationsTiedToScroll,
  objectClump,
  htmlInputFields,
  useintersectAndScrollcontrols,
  infiniteScroll,
  scrollcontrolsWithMinimap,
  instancedParticlesEffects,
  dbismutFurniture,
  portalShapes,
  aquarium,
  portals,
  interEpoxyResin,
  stagePresetsGltfjsx,
  reactEllipsecurve,
  iridescentDecals,
  bakingSoftShadows,
  ssrTest,
  csgOperationsRapierPhysics,
  faucetsSelectHighlight,
  rapierPhysics,
  bloomHdrWorkflowGltf,
  groundProjectedEnvmapsLamina,
  basicBallpit,
  backdropAndCables,
  clones,
  lamina1x,
  reactPpOutlines,
  gatsbyStars,
  pmndrsVercel,
  sportHall,
  nightTrain,
  bouncyWatch,
  transparentAesopBottles,
  raycastCycling,
  landingPage,
  scrollcontrolsGltf,
  mergedInstance,
  gpgpuCurlNoiseDof,
  hiKeyBubbles,
  floatingInstancedShoes,
  simpleAudioAnalyser,
  cameraScroll,
  springyBoxes,
  floatingDiamonds,
  gltfAnimations,
  sparksAndEffects,
  cameraShake,
  ragdollPhysics,
  reactSpringAnimations,
  mountTransitions,
  floatingLaptop,
  zustandSite,
  cellFracture,
  routerTransitions,
  softShadows,
  lulabyCity,
  vikingShip,
  wobblingSphere,
  moksha,
  flexboxYogaInWebgl,
  confetti,
  learnWithJason,
  volumetricSpotlight,
  // Game Prototypes
  racingGame,
  pinballIn70Lines,
  spaceGame,
  minecraft,
  arkanoid,
  pingPong,
  arkanoidUnder60Loc,
  // Basic Examples
  basicDemo,
  dreiRenderTexture,
  bvh,
  environmentBlurAndTransitions,
  pairingThreejsToUI,
  invertedStencilBuffer,
  stencilMask,
  transformControlsAndMakeDefault,
  boundsandMakeDefault,
  instancedVertexColors,
  progressiveLoadingStatesWithSuspense,
  viewTracking,
  multipleViewsWithUniformControls,
  canvasAndText,
  gltfAnimationsReused,
  reusingGltfs,
  svgRenderer,
  mixingHtmlandWebgl,
  viewcube,
  mixingControls,
  videoTextures,
  skyDomeWithAnnotations,
  tyingCanvasToScrollOffset,
  edgesGeometry,
  htmlAnnotations,
  shaderMaterials,
  simplePhysicsDemo,
  triggerMeshes,
  simplePhysicsDemoWithDebugBounds,
  selectiveOutlines,
  instances,
  physicsWithConvexPolyhedrons,
  colorGrading,
  grassShader,
  clouds,
  svgMapsWithHtmlAnnotations,
  reusingGeometryAndLevelOfDetail,
  htmlMarkers,
  bezierCurvesAndNodes,
  shaderFire,
  waterShader,
  stagingAndCameraShake,
  shaderHmr,
} from '../assets';
import { getSystemTheme } from '../utils/utils';

export const dataStore = create((set) => ({
  theme: getSystemTheme(),
  setTheme: (theme) => set({ theme }),
  toggleTheme: () => set((state) => ({ theme: state.theme === 'light' ? 'dark' : 'light' })),

  logoPosition: 'top right',
  setLogoPosition: (logoPosition) => set({ logoPosition }),

  tab: 'showcase',
  setTab: (tab) => set({ tab }),

  data: {
    showcase: [
      {
        title: 'Monitors',
        path: 'monitors',
        image: monitors,
        link: 'https://codesandbox.io/s/bst0cy',
      },
      {
        title: 'Flying Bananas',
        path: 'flying-bananas',
        image: flyingBananas,
        link: 'https://codesandbox.io/s/2ycs3',
      },
      {
        title: 'Room With Soft Shadows',
        path: 'room-with-soft-shadows',
        image: roomWithSoftShadows,
        link: 'https://codesandbox.io/s/ykfpwf',
      },
      {
        title: 'Tshirt Configurator',
        path: 'tshirt-configurator',
        image: tshirtConfigurator,
        link: 'https://codesandbox.io/s/ioxywi',
      },
      {
        title: 'Caustics',
        path: 'caustics',
        image: caustics,
        link: 'https://codesandbox.io/s/szj6p7',
      },
      {
        title: 'Volumetric Light Godray',
        path: 'volumetric-light-godray',
        image: volumetricLightGodray,
        link: 'https://codesandbox.io/s/yggpw5',
      },
      {
        title: 'Enter Portals',
        path: 'enter-portals',
        image: enterPortals,
        link: 'https://codesandbox.io/s/9m4tpc',
      },
      {
        title: 'Pass Through Portals',
        path: 'pass-through-portals',
        image: passThroughPortals,
        link: 'https://codesandbox.io/s/qvk72r',
      },
      {
        title: 'Magic Box',
        path: 'magic-box',
        image: magicBox,
        link: 'https://codesandbox.io/s/drc6qg',
      },
      {
        title: 'Glass Flower',
        path: 'glass-flower',
        image: glassFlower,
        link: 'https://codesandbox.io/s/dq6wwe',
      },
      {
        title: 'Image Gallery',
        path: 'image-gallery',
        image: imageGallery,
        link: 'https://codesandbox.io/s/lx2h8',
      },
      {
        title: 'Horizontal Tiles',
        path: 'horizontal-tiles',
        image: horizontalTiles,
        link: 'https://codesandbox.io/s/l4klb',
      },
      {
        title: 'Best Served Bold Christmas Baubles',
        path: 'best-served-bold-christmas-baubles',
        image: bestServedBoldChristmasBaubles,
        link: 'https://codesandbox.io/s/zxpv7',
      },
      {
        title: 'The Three Graces',
        path: 'the-three-graces',
        image: theThreeGraces,
        link: 'https://codesandbox.io/s/0n9it',
      },
      {
        title: 'Frosted Glass',
        path: 'frosted-glass',
        image: frostedGlass,
        link: 'https://codesandbox.io/s/imn42',
      },
      {
        title: 'Gltfjsx-400kb Drone',
        path: 'gltfjsx-400kb-drone',
        image: gltfjsx400kbDrone,
        link: 'https://codesandbox.io/s/pbwi6i',
      },
      {
        title: 'Star Wars',
        path: 'star-wars',
        image: starWars,
        link: 'https://codesandbox.io/s/fslt99',
      },
      {
        title: 'Bruno Simons-20k Challenge',
        path: 'bruno-simons-20k-challenge',
        image: brunoSimons20kChallenge,
        link: 'https://codesandbox.io/s/2qfxj4',
      },
      {
        title: 'Scrollcontrols And Lens Refraction',
        path: 'scrollcontrols-and-lens-refraction',
        image: scrollcontrolsAndLensRefraction,
        link: 'https://codesandbox.io/s/2n98yj',
      },
      {
        title: 'Building Dynamic Envmaps',
        path: 'building-dynamic-envmaps',
        image: buildingDynamicEnvmaps,
        link: 'https://codesandbox.io/s/e662p3',
      },
      {
        title: 'Nextjs Prism',
        path: 'nextjs-prism',
        image: nextjsPrism,
        link: 'https://codesandbox.io/s/j3ycvl',
      },
      {
        title: 'Building Live Envmaps',
        path: 'building-live-envmaps',
        image: buildingLiveEnvmaps,
        link: 'https://codesandbox.io/s/lwo219',
      },
      {
        title: 'Shoe Configurator',
        path: 'shoe-configurator',
        image: shoeConfigurator,
        link: 'https://codesandbox.io/s/qxjoj',
      },
      {
        title: 'Audio Analyser',
        path: 'audio-analyser',
        image: audioAnalyser,
        link: 'https://codesandbox.io/s/dvokj',
      },
      {
        title: 'Ground Reflections And Video Textures',
        path: 'ground-reflections-and-video-textures',
        image: groundReflectionsAndVideoTextures,
        link: 'https://codesandbox.io/s/bfplr',
      },
      {
        title: 'Threejs Journey Lv1',
        path: 'threejs-journey-lv1',
        image: threejsJourneyLv1,
        link: 'https://codesandbox.io/s/kheke',
      },
      {
        title: 'Threejs Journey Portal',
        path: 'threejs-journey-portal',
        image: threejsJourneyPortal,
        link: 'https://codesandbox.io/s/ni6v4',
      },
      {
        title: 'Mixing Html And Webgl W Occlusion',
        path: 'mixing-html-and-webgl-w-occlusion',
        image: mixingHtmlAndWebglWithOcclusion,
        link: 'https://codesandbox.io/s/9keg6',
      },
      {
        title: 'Interactive Spline Scene Live Html',
        path: 'interactive-spline-scene-live-html',
        image: interactiveSplineSceneLiveHtml,
        link: 'https://codesandbox.io/s/f79ucc',
      },
      {
        title: 'Diamond Refraction',
        path: 'diamond-refraction',
        image: diamondRefraction,
        link: 'https://codesandbox.io/s/zqrreo',
      },
      {
        title: 'Diamond Ring',
        path: 'diamond-ring',
        image: diamondRing,
        link: 'https://codesandbox.io/s/4gy946',
      },
      {
        title: 'Envmap Ground Projection',
        path: 'envmap-ground-projection',
        image: envmapGroundProjection,
        link: 'https://codesandbox.io/s/q48jgy',
      },
      {
        title: 'Spline Glass Shapes',
        path: 'spline-glass-shapes',
        image: splineGlassShapes,
        link: 'https://codesandbox.io/s/ju368j',
      },
      {
        title: 'Csg Bunny Usegroups',
        path: 'csg-bunny-usegroups',
        image: csgBunnyUsegroups,
        link: 'https://codesandbox.io/s/mlgzsc',
      },
      {
        title: 'Csg House',
        path: 'csg-house',
        image: csgHouse,
        link: 'https://codesandbox.io/s/y52tmt',
      },
      {
        title: 'Gltf Animations Tied To Scroll',
        path: 'gltf-animations-tied-to-scroll',
        image: gltfAnimationsTiedToScroll,
        link: 'https://codesandbox.io/s/hg3ejl',
      },
      {
        title: 'Object Clump',
        path: 'object-clump',
        image: objectClump,
        link: 'https://codesandbox.io/s/ssbdsw',
      },
      {
        title: 'Html Input Fields',
        path: 'html-input-fields',
        image: htmlInputFields,
        link: 'https://codesandbox.io/s/024uom',
      },
      {
        title: 'Useintersect And Scrollcontrols',
        path: 'useintersect-and-scrollcontrols',
        image: useintersectAndScrollcontrols,
        link: 'https://codesandbox.io/s/gsm1y',
      },
      {
        title: 'Infinite Scroll',
        path: 'infinite-scroll',
        image: infiniteScroll,
        link: 'https://codesandbox.io/s/x8gvs',
      },
      {
        title: 'Scrollcontrols With Minimap',
        path: 'scrollcontrols-with-minimap',
        image: scrollcontrolsWithMinimap,
        link: 'https://codesandbox.io/s/yjhzv',
      },
      {
        title: 'Instanced Particles Effects',
        path: 'instanced-particles-effects',
        image: instancedParticlesEffects,
        link: 'https://codesandbox.io/s/qpfgyp',
      },
      {
        title: 'Dbismut Furniture',
        path: 'dbismut-furniture',
        image: dbismutFurniture,
        link: 'https://codesandbox.io/s/62o18n',
      },
      {
        title: 'Portal Shapes',
        path: 'portal-shapes',
        image: portalShapes,
        link: 'https://codesandbox.io/s/8j36ok',
      },
      {
        title: 'Aquarium',
        path: 'aquarium',
        image: aquarium,
        link: 'https://codesandbox.io/s/n7jf0f',
      },
      {
        title: 'Portals',
        path: 'portals',
        image: portals,
        link: 'https://codesandbox.io/s/ik11ln',
      },
      {
        title: 'Inter Epoxy Resin',
        path: 'inter-epoxy-resin',
        image: interEpoxyResin,
        link: 'https://codesandbox.io/s/lxvqek',
      },
      {
        title: 'Stage Presets Gltfjsx',
        path: 'stage-presets-gltfjsx',
        image: stagePresetsGltfjsx,
        link: 'https://codesandbox.io/s/if9crg',
      },
      {
        title: 'React Ellipsecurve',
        path: 'react-ellipsecurve',
        image: reactEllipsecurve,
        link: 'https://codesandbox.io/s/xzi6ps',
      },
      {
        title: 'Iridescent Decals',
        path: 'iridescent-decals',
        image: iridescentDecals,
        link: 'https://codesandbox.io/s/qvb1vk',
      },
      {
        title: 'Baking Soft Shadows',
        path: 'baking-soft-shadows',
        image: bakingSoftShadows,
        link: 'https://codesandbox.io/s/hxcc1x',
      },
      {
        title: 'Ssr Test',
        path: 'ssr-test',
        image: ssrTest,
        link: 'https://codesandbox.io/s/8pbw1f',
      },
      {
        title: 'Csg Operations Rapier Physics',
        path: 'csg-operations-rapier-physics',
        image: csgOperationsRapierPhysics,
        link: 'https://codesandbox.io/s/mw0dtc',
      },
      {
        title: 'Faucets Select Highlight',
        path: 'faucets-select-highlight',
        image: faucetsSelectHighlight,
        link: 'https://codesandbox.io/s/8flefh',
      },
      {
        title: 'Rapier Physics',
        path: 'rapier-physics',
        image: rapierPhysics,
        link: 'https://codesandbox.io/s/7e9y1b',
      },
      {
        title: 'Bloom Hdr Workflow Gltf',
        path: 'bloom-hdr-workflow-gltf',
        image: bloomHdrWorkflowGltf,
        link: 'https://codesandbox.io/s/whnhyr',
      },
      {
        title: 'Ground Projected Envmaps Lamina',
        path: 'ground-projected-envmaps-lamina',
        image: groundProjectedEnvmapsLamina,
        link: 'https://codesandbox.io/s/0c5hv9',
      },
      {
        title: 'Basic Ballpit',
        path: 'basic-ballpit',
        image: basicBallpit,
        link: 'https://codesandbox.io/s/0fqow2',
      },
      {
        title: 'Backdrop And Cables',
        path: 'backdrop-and-cables',
        image: backdropAndCables,
        link: 'https://codesandbox.io/s/2ij9u',
      },
      {
        title: 'Clones',
        path: 'clones',
        image: clones,
        link: 'https://codesandbox.io/s/42glz0',
      },
      {
        title: 'Lamina-1x',
        path: 'lamina-1x',
        image: lamina1x,
        link: 'https://codesandbox.io/s/ledhe1',
      },
      {
        title: 'React Pp Outlines',
        path: 'react-pp-outlines',
        image: reactPpOutlines,
        link: 'https://codesandbox.io/s/nurp5t',
      },
      {
        title: 'Gatsby Stars',
        path: 'gatsby-stars',
        image: gatsbyStars,
        link: 'https://codesandbox.io/s/2csbr1',
      },
      {
        title: 'Pmndrs Vercel',
        path: 'pmndrs-vercel',
        image: pmndrsVercel,
        link: 'https://codesandbox.io/s/go0b4w',
      },
      {
        title: 'Sport Hall',
        path: 'sport-hall',
        image: sportHall,
        link: 'https://codesandbox.io/s/s006f',
      },
      {
        title: 'Night Train',
        path: 'night-train',
        image: nightTrain,
        link: 'https://codesandbox.io/s/l900i',
      },
      {
        title: 'Bouncy Watch',
        path: 'bouncy-watch',
        image: bouncyWatch,
        link: 'https://codesandbox.io/s/qyz5r',
      },
      {
        title: 'Transparent Aesop Bottles',
        path: 'transparent-aesop-bottles',
        image: transparentAesopBottles,
        link: 'https://codesandbox.io/s/kv7tv',
      },
      {
        title: 'Raycast Cycling',
        path: 'raycast-cycling',
        image: raycastCycling,
        link: 'https://codesandbox.io/s/ls503',
      },
      {
        title: 'Landing Page',
        path: 'landing-page',
        image: landingPage,
        link: 'https://codesandbox.io/s/n60qg',
      },
      {
        title: 'Scrollcontrols Gltf',
        path: 'scrollcontrols-gltf',
        image: scrollcontrolsGltf,
        link: 'https://codesandbox.io/s/4jr4p',
      },
      {
        title: 'Merged-Instance',
        path: 'merged-instance',
        image: mergedInstance,
        link: 'https://codesandbox.io/s/kud9p',
      },
      {
        title: 'Gpgpu Curl Noise Dof',
        path: 'gpgpu-curl-noise-dof',
        image: gpgpuCurlNoiseDof,
        link: 'https://codesandbox.io/s/zgsyn',
      },
      {
        title: 'Hi Key Bubbles',
        path: 'hi-key-bubbles',
        image: hiKeyBubbles,
        link: 'https://codesandbox.io/s/i6t0j',
      },
      {
        title: 'Floating Instanced Shoes',
        path: 'floating-instanced-shoes',
        image: floatingInstancedShoes,
        link: 'https://codesandbox.io/s/h8o2d',
      },
      {
        title: 'Simple Audio Analyser',
        path: 'simple-audio-analyser',
        image: simpleAudioAnalyser,
        link: 'https://codesandbox.io/s/wu51m',
      },
      {
        title: 'Camera Scroll',
        path: 'camera-scroll',
        image: cameraScroll,
        link: 'https://codesandbox.io/s/tu24h',
      },
      {
        title: 'Springy Boxes',
        path: 'springy-boxes',
        image: springyBoxes,
        link: 'https://codesandbox.io/s/jz9l97qn89',
      },
      {
        title: 'Floating Diamonds',
        path: 'floating-diamonds',
        image: floatingDiamonds,
        link: 'https://codesandbox.io/s/prb9t',
      },
      {
        title: 'Gltf Animations',
        path: 'gltf-animations',
        image: gltfAnimations,
        link: 'https://codesandbox.io/s/pecl6',
      },
      {
        title: 'Sparks And Effects',
        path: 'sparks-and-effects',
        image: sparksAndEffects,
        link: 'https://codesandbox.io/s/sbf2i',
      },
      {
        title: 'Camera Shake',
        path: 'camera-shake',
        image: cameraShake,
        link: 'https://codesandbox.io/s/t4l0f',
      },
      {
        title: 'Ragdoll Physics',
        path: 'ragdoll-physics',
        image: ragdollPhysics,
        link: 'https://codesandbox.io/s/wdzv4',
      },
      {
        title: 'React Spring Animations',
        path: 'react-spring-animations',
        image: reactSpringAnimations,
        link: 'https://codesandbox.io/s/6hi1y',
      },
      {
        title: 'Mount Transitions',
        path: 'mount-transitions',
        image: mountTransitions,
        link: 'https://codesandbox.io/s/1sccp',
      },
      {
        title: 'Floating Laptop',
        path: 'floating-laptop',
        image: floatingLaptop,
        link: 'https://codesandbox.io/s/q23sw',
      },
      {
        title: 'Zustand Site',
        path: 'zustand-site',
        image: zustandSite,
        link: 'https://codesandbox.io/s/gpioq',
      },
      {
        title: 'Cell Fracture',
        path: 'cell-fracture',
        image: cellFracture,
        link: 'https://codesandbox.io/s/3rjsl',
      },
      {
        title: 'Router Transitions',
        path: 'router-transitions',
        image: routerTransitions,
        link: 'https://codesandbox.io/s/4j2q2',
      },
      {
        title: 'Soft Shadows',
        path: 'soft-shadows',
        image: softShadows,
        link: 'https://codesandbox.io/s/dh2jc',
      },
      {
        title: 'Lulaby City',
        path: 'lulaby-city',
        image: lulabyCity,
        link: 'https://codesandbox.io/s/gkfhr',
      },
      {
        title: 'Viking Ship',
        path: 'viking-ship',
        image: vikingShip,
        link: 'https://codesandbox.io/s/0buje',
      },
      {
        title: 'Wobbling Sphere',
        path: 'wobbling-sphere',
        image: wobblingSphere,
        link: 'https://codesandbox.io/s/5oufp',
      },
      {
        title: 'Moksha',
        path: 'moksha',
        image: moksha,
        link: 'https://codesandbox.io/s/f1ixt',
      },
      {
        title: 'Flexbox Yoga In Webgl',
        path: 'flexbox-yoga-in-webgl',
        image: flexboxYogaInWebgl,
        link: 'https://codesandbox.io/s/7psew',
      },
      {
        title: 'Confetti',
        path: 'confetti',
        image: confetti,
        link: 'https://codesandbox.io/s/vl221',
      },
      {
        title: 'Learn With Jason',
        path: 'learn-with-jason',
        image: learnWithJason,
        link: 'https://codesandbox.io/s/oep9o',
      },
      {
        title: 'Volumetric Spotlight',
        path: 'volumetric-spotlight',
        image: volumetricSpotlight,
        link: 'https://codesandbox.io/s/tx1pq',
      },
    ],
    'game prototypes': [
      {
        title: 'Racing Game',
        path: 'racing-game',
        image: racingGame,
        link: 'https://codesandbox.io/s/lo6kp',
      },
      {
        title: 'Pinball In 70 Lines',
        path: 'pinball-in-70-lines',
        image: pinballIn70Lines,
        link: 'https://codesandbox.io/s/rmfcq',
      },
      {
        title: 'Space Game',
        path: 'space-game',
        image: spaceGame,
        link: 'https://codesandbox.io/s/i2160',
      },
      {
        title: 'Minecraft',
        path: 'Arkanoid',
        image: minecraft,
        link: 'https://codesandbox.io/s/vkgi6',
      },
      {
        title: 'Arkanoid',
        path: 'Ping-Pong',
        image: arkanoid,
        link: 'https://codesandbox.io/s/2yqpv',
      },
      {
        title: 'Ping-Pong',
        path: 'ping-pong',
        image: pingPong,
        link: 'https://codesandbox.io/s/0mgum',
      },
      {
        title: 'Arkanoid Under 60 LOC',
        path: 'arkanoid-under-60-loc',
        image: arkanoidUnder60Loc,
        link: 'https://codesandbox.io/s/66cd7',
      },
    ],
    'basic examples': [
      {
        title: 'Basic Demo',
        path: 'basic-demo',
        image: basicDemo,
        link: 'https://codesandbox.io/s/rrppl0y8l4',
      },
      {
        title: 'Drei Render Texture',
        path: 'drei-render-texture',
        image: dreiRenderTexture,
        link: 'https://codesandbox.io/s/0z8i2c',
      },
      {
        title: 'BVH',
        path: 'bvh',
        image: bvh,
        link: 'https://codesandbox.io/s/txzeq8',
      },
      {
        title: 'Environment Blur and Transitions',
        path: 'environment-blur-and-transitions',
        image: environmentBlurAndTransitions,
        link: 'https://codesandbox.io/s/pj7zjq',
      },
      {
        title: 'Pairing Threejs To UI',
        path: 'pairing-threejs-to-ui',
        image: pairingThreejsToUI,
        link: 'https://codesandbox.io/s/wlz1o0',
      },
      {
        title: 'Inverted Stencil Buffer',
        path: 'inverted-stencil-buffer',
        image: invertedStencilBuffer,
        link: 'https://codesandbox.io/s/7n2yru',
      },
      {
        title: 'Stencil Mask',
        path: 'stencil-mask',
        image: stencilMask,
        link: 'https://codesandbox.io/s/z3f2mw',
      },
      {
        title: 'TransformControls And Make Default',
        path: 'transformcontrols-and-make-default',
        image: transformControlsAndMakeDefault,
        link: 'https://codesandbox.io/s/btsbj',
      },
      {
        title: 'Bounds and Make Default',
        path: 'bounds-and-make-default',
        image: boundsandMakeDefault,
        link: 'https://codesandbox.io/s/rz2g0',
      },
      {
        title: 'Instanced Vertex Colors',
        path: 'instanced-vertex-colors',
        image: instancedVertexColors,
        link: 'https://codesandbox.io/s/8fo01',
      },
      {
        title: 'Progressive Loading States With Suspense',
        path: 'progressive-loading-states-with-suspense',
        image: progressiveLoadingStatesWithSuspense,
        link: 'https://codesandbox.io/s/7duy8',
      },
      {
        title: 'View Tracking',
        path: 'view-tracking',
        image: viewTracking,
        link: 'https://codesandbox.io/s/bp6tmc',
      },
      {
        title: 'Multiple Views With Uniform Controls',
        path: 'multiple-views-with-uniform-controls',
        image: multipleViewsWithUniformControls,
        link: 'https://codesandbox.io/s/r9w2ob',
      },
      {
        title: 'Canvas And Text',
        path: 'canvas-and-text',
        image: canvasAndText,
        link: 'https://codesandbox.io/s/p9umgf',
      },
      {
        title: 'GLTF Animations Reused',
        path: 'gltf-animations-reused',
        image: gltfAnimationsReused,
        link: 'https://codesandbox.io/s/k8phr',
      },
      {
        title: 'Reusing Gltfs',
        path: 'reusing-gltfs',
        image: reusingGltfs,
        link: 'https://codesandbox.io/s/dix1y',
      },
      {
        title: 'Svg Renderer',
        path: 'svg-renderer',
        image: svgRenderer,
        link: 'https://codesandbox.io/s/zcuqh',
      },
      {
        title: 'Mixing Html and Webgl',
        path: 'mixing-html-and-webgl',
        image: mixingHtmlandWebgl,
        link: 'https://codesandbox.io/s/7ucso',
      },
      {
        title: 'Viewcube',
        path: 'viewcube',
        image: viewcube,
        link: 'https://codesandbox.io/s/py4db',
      },
      {
        title: 'Mixing Controls',
        path: 'mixing-controls',
        image: mixingControls,
        link: 'https://codesandbox.io/s/hf1cs',
      },
      {
        title: 'Video Textures',
        path: 'video-textures',
        image: videoTextures,
        link: 'https://codesandbox.io/s/39hg8',
      },
      {
        title: 'Sky Dome With Annotations',
        path: 'sky-dome-with-annotations',
        image: skyDomeWithAnnotations,
        link: 'https://codesandbox.io/s/wbrfs',
      },
      {
        title: 'Tying Canvas To Scroll Offset',
        path: 'tying-canvas-to-scroll-offset',
        image: tyingCanvasToScrollOffset,
        link: 'https://codesandbox.io/s/itfgk',
      },
      {
        title: 'Edges Geometry',
        path: 'edges-geometry',
        image: edgesGeometry,
        link: 'https://codesandbox.io/s/iup24',
      },
      {
        title: 'Html Annotations',
        path: 'html-annotations',
        image: htmlAnnotations,
        link: 'https://codesandbox.io/s/zu2wo',
      },
      {
        title: 'Shader Materials',
        path: 'shader-materials',
        image: shaderMaterials,
        link: 'https://codesandbox.io/s/1g4qq',
      },
      {
        title: 'Simple Physics Demo',
        path: 'simple-physics-demo',
        image: simplePhysicsDemo,
        link: 'https://codesandbox.io/s/z8e6m',
      },
      {
        title: 'Trigger Meshes',
        path: 'trigger-meshes',
        image: triggerMeshes,
        link: 'https://codesandbox.io/s/h545c',
      },
      {
        title: 'Simple Physics Demo With Debug Bounds',
        path: 'simple-physics-demo-with-debug-bounds',
        image: simplePhysicsDemoWithDebugBounds,
        link: 'https://codesandbox.io/s/0k27n',
      },
      {
        title: 'Selective Outlines',
        path: 'selective-outlines',
        image: selectiveOutlines,
        link: 'https://codesandbox.io/s/d36mw',
      },
      {
        title: 'Instances',
        path: 'instances',
        image: instances,
        link: 'https://codesandbox.io/s/h873k',
      },
      {
        title: 'Physics With Convex Polyhedrons',
        path: 'physics-with-convex-polyhedrons',
        image: physicsWithConvexPolyhedrons,
        link: 'https://codesandbox.io/s/08s1u',
      },
      {
        title: 'Color Grading',
        path: 'color-grading',
        image: colorGrading,
        link: 'https://codesandbox.io/s/wvgxp',
      },
      {
        title: 'Grass Shader',
        path: 'grass-shader',
        image: grassShader,
        link: 'https://codesandbox.io/s/5xho4',
      },
      {
        title: 'Clouds',
        path: 'clouds',
        image: clouds,
        link: 'https://codesandbox.io/s/mbfzf',
      },
      {
        title: 'Svg Maps With Html Annotations',
        path: 'svg-maps-with-html-annotations',
        image: svgMapsWithHtmlAnnotations,
        link: 'https://codesandbox.io/s/mkq8e',
      },
      {
        title: 'Reusing Geometry And Level Of Detail',
        path: 'reusing-geometry-and-level-of-detail',
        image: reusingGeometryAndLevelOfDetail,
        link: 'https://codesandbox.io/s/12nmp',
      },
      {
        title: 'Html Markers',
        path: 'html-markers',
        image: htmlMarkers,
        link: 'https://codesandbox.io/s/6oei7',
      },
      {
        title: 'Bezier Curves And Nodes',
        path: 'bezier-curves-and-nodes',
        image: bezierCurvesAndNodes,
        link: 'https://codesandbox.io/s/3k4g6',
      },
      {
        title: 'Shader Fire',
        path: 'shader-fire',
        image: shaderFire,
        link: 'https://codesandbox.io/s/3878x',
      },
      {
        title: 'Water Shader',
        path: 'water-shader',
        image: waterShader,
        link: 'https://codesandbox.io/s/1b40u',
      },
      {
        title: 'Staging And CameraShake',
        path: 'staging-and-camerashake',
        image: stagingAndCameraShake,
        link: 'https://codesandbox.io/s/0ycwe',
      },
      {
        title: 'Shader Hmr',
        path: 'shader-hmrshader-hmr',
        image: shaderHmr,
        link: 'https://codesandbox.io/s/ib0jc',
      },
    ],
  },
}));
